<script setup>
/** Vendor */
import { Buffer } from "buffer"

/** Components: Hex Viewer */
import HexViewer from "@/components/modules/hex/HexViewer.vue"
import DataInspector from "@/components/modules/hex/DataInspector.vue"

useSeoMeta({
	title: "Astrotrek Hex Viewer",
})

const data =
	"+QFQggs0hQM9ZgzAgwehIJQpu6/yFpX6QeRGxPN8B8aZ2fCAIYC45ATkWq8AAAAAAAAAAAAAAABht3lLagzDg7Nnwye5HluoWRWgcQAAAAAAAAAAAAAAAD9lFE84f2VFv0sZobOclCMeHISfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7gAAAAAAAAAAAAAAAAdMoajNI+pmFLRR8V6eQRbQcT3EwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIIasNRBSYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGJLuWEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQeNC8goIMIj8cRr220BqNoUKHHyRl4w49SX/II8rTROUGcK1NioBjMwHmMavnI1qfe1Z5fRI/uOiuwSy8yn9mr7D/j03k8+QFQggs0hQM9ZgzAgwehIJQpu6/yFpX6QeRGxPN8B8aZ2fCAIYC45ATkWq8AAAAAAAAAAAAAAABht3lLagzDg7Nnwye5HluoWRWgcQAAAAAAAAAAAAAAAD9lFE84f2VFv0sZobOclCMeHISfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7gAAAAAAAAAAAAAAAAdMoajNI+pmFLRR8V6eQRbQcT3EwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIIasNRBSYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGJLuWEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQeNC8goIMIj8cRr220BqNoUKHHyRl4w49SX/II8rTROUGcK1NioBjMwHmMavnI1qfe1Z5fRI/uOiuwSy8yn9mr7D/j03k8+QFQggs0hQM9ZgzAgwehIJQpu6/yFpX6QeRGxPN8B8aZ2fCAIYC45ATkWq8AAAAAAAAAAAAAAABht3lLagzDg7Nnwye5HluoWRWgcQAAAAAAAAAAAAAAAD9lFE84f2VFv0sZobOclCMeHISfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7gAAAAAAAAAAAAAAAAdMoajNI+pmFLRR8V6eQRbQcT3EwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIIasNRBSYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGJLuWEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQeNC8goIMIj8cRr220BqNoUKHHyRl4w49SX/II8rTROUGcK1NioBjMwHmMavnI1qfe1Z5fRI/uOiuwSy8yn9mr7D/j03k8+QFQggs0hQM9ZgzAgwehIJQpu6/yFpX6QeRGxPN8B8aZ2fCAIYC45ATkWq8AAAAAAAAAAAAAAABht3lLagzDg7Nnwye5HluoWRWgcQAAAAAAAAAAAAAAAD9lFE84f2VFv0sZobOclCMeHISfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7gAAAAAAAAAAAAAAAAdMoajNI+pmFLRR8V6eQRbQcT3EwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIIasNRBSYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGJLuWEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQeNC8goIMIj8cRr220BqNoUKHHyRl4w49SX/II8rTROUGcK1NioBjMwHmMavnI1qfe1Z5fRI/uOiuwSy8yn9mr7D/j03k8+QFQggs0hQM9ZgzAgwehIJQpu6/yFpX6QeRGxPN8B8aZ2fCAIYC45ATkWq8AAAAAAAAAAAAAAABht3lLagzDg7Nnwye5HluoWRWgcQAAAAAAAAAAAAAAAD9lFE84f2VFv0sZobOclCMeHISfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7gAAAAAAAAAAAAAAAAdMoajNI+pmFLRR8V6eQRbQcT3EwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIIasNRBSYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGJLuWEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQeNC8goIMIj8cRr220BqNoUKHHyRl4w49SX/II8rTROUGcK1NioBjMwHmMavnI1qfe1Z5fRI/uOiuwSy8yn9mr7D/j03k8+QFQggs0hQM9ZgzAgwehIJQpu6/yFpX6QeRGxPN8B8aZ2fCAIYC45ATkWq8AAAAAAAAAAAAAAABht3lLagzDg7Nnwye5HluoWRWgcQAAAAAAAAAAAAAAAD9lFE84f2VFv0sZobOclCMeHISfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7gAAAAAAAAAAAAAAAAdMoajNI+pmFLRR8V6eQRbQcT3EwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIIasNRBSYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGJLuWEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQeNC8goIMIj8cRr220BqNoUKHHyRl4w49SX/II8rTROUGcK1NioBjMwHmMavnI1qfe1Z5fRI/uOiuwSy8yn9mr7D/j03k8"
// const data =
// 	"+QFQggs0hQM9ZgzAgwehIJQpu6/yFpX6QeRGxPN8B8aZ2fCAIYC45ATkWq8AAAAAAAAAAAAAAABht3lLagzDg7Nnwye5HluoWRWgcQAAAAAAAAAAAAAAAD9lFE84f2VFv0sZobOclCMeHISfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7gAAAAAAAAAAAAAAAAdMoajNI+pmFLRR8V6eQRbQcT3EwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIIasNRBSYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGJLuWEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIQeNC8goIMIj8cRr220BqNoUKHHyRl4w49SX/II8rTROUGcK1NioBjMwHmMavnI1qfe1Z5fRI/uOiuwSy8yn9mr7D/j03k8"
const hex = ref([])
const size = ref(0)
const bytes = computed(() => {
	return hex.value.flat()
})

/** Selected byte (1) */
const cursor = ref(0)
const handleSelectCursor = (target) => {
	if (target < 0 || target > bytes.value.length) return
	cursor.value = target
}
/** Range of selected bytes */
const range = reactive({ start: 0, end: 0 })
const handleBytesSelect = (selection) => {
	const [start, end] = selection

	if (start !== undefined) {
		range.start = start
	}
	if (end !== undefined) {
		range.end = end
	}
}

onMounted(() => {
	const buffer = Buffer.from(data, "base64")
	size.value = Buffer.byteLength(buffer)

	hex.value = buffer
		.toString("hex")
		.match(/../g)
		.reduce((acc, current, idx) => {
			const chunkIdx = Math.floor(idx / 16)
			acc[chunkIdx] = acc[chunkIdx] || []
			acc[chunkIdx].push(current)
			return acc
		}, [])
})
</script>

<template>
	<Flex wide :class="$style.wrapper">
		<ClientOnly>
			<HexViewer :hex :bytes :cursor :range :size @onSelect="handleBytesSelect" @onCursorSelect="handleSelectCursor" />
			<DataInspector :bytes="bytes" :range="range" :cursor="cursor" />
		</ClientOnly>
	</Flex>
</template>

<style module>
.wrapper {
	max-width: calc(var(--base-width) + 48px);

	margin-top: 24px;
	margin-bottom: 120px;
	padding: 0 24px;
}
</style>
